### ISSUE TITLE
Form input items are hijacking autocomplete dropdown selection

### ISSUE THREAD

**Issue by albertywu** [rivo/tview#1048]
I'm running into an issue where when an autocomplete dropdown item overlaps with another form field input item, the form input item takes click precedence and "hijacks" the click. See example below:

![autocomplete](https://github.com/user-attachments/assets/5d7312ef-9d39-4f12-8764-6df4a85a1e95)

^ Example adapted from the autocomplete demo [here](https://github.com/rivo/tview/blob/master/demos/inputfield/autocomplete/main.go)

Is there a way to specify that the autocomplete dropdown items have higher "zIndex" than other items in the form so this doesn't happen? If not, what is the recommended approach for handling this scenario?

**Comment by rivo** [comment]
This was a bug. The latest commit should fix this.

**Comment by albertywu** [comment]
Thanks for the super fast response @rivo. Unfortunately commit 8808192 didn't fix the issue. I don't think it's about when the autocomplete gets rendered (it's getting rendered fine). The issue is that mouse-clicking on an autocomplete that overlaps with a form field doesn't work because the form field steals the click (see original gif).
