### ISSUE TITLE
pasting to the TextArea

### ISSUE THREAD

**Issue by GrailFinder** [rivo/tview#1062]
Hello.  
Pasting text to the `TextArea` has some unpleasant moments:
- text is inserted by char (with delay);
- formatting is broken (at least whitespaces are (\n \t));  

video example (linux; xorg; neovim):
https://github.com/user-attachments/assets/7e498f8b-a739-422c-b3f0-553d8ef625bb

Is there a better way to paste?

**Comment by rivo** [comment]
This is explicitly addressed in `TextArea`'s documentation:

https://pkg.go.dev/github.com/rivo/tview#hdr-Navigation_and_Editing-TextArea

> Note that using your terminal's / operating system's key bindings for copy+paste functionality may not have the expected effect as tview will not be able to handle these keys. Pasting text using your operating system's or terminal's own methods may be very slow as each character will be pasted individually. However, some terminals support pasting text blocks which is supported by the text area, see [Application.EnablePaste](https://pkg.go.dev/github.com/rivo/tview#Application.EnablePaste) for details.

**Comment by svanharmelen** [comment]
I am using the suggested `Application.EnablePaste`, and while it does speed up (improve) pasting it still doesn't fix the formatting issues. So if I paste a block of text which consists of several lines, I end up with a single line. So all the newlines are not handled correctly. Is there an option or setting that I need to configure for it to paste the text as is?

Example:
```
Hello
how
are
you
doing?
```
When copy/pasted end up like this:
```
Hellohowareyoudoing?
```

Thanks!

**Comment by ivoGanev** [comment]
`Application.EnablePaste` doesn’t seem to work on a Windows terminal, so I was wondering if there can be anything else done about totally disabling paste in a TextArea. I was able to redirect the key bindings to use other keys for pasting, but I am worried about what kind of experience it is going to be for a user who is used to using the 'Ctrl+V' shortcut. I imagine they will assume the app has a terrible copy/paste experience and quit using it.

**Comment by rivo** [comment]
I don't think there is a way to change the settings of a terminal application from within. At least I'm not aware of one.
